#!/usr/bin/env bash

tex_file=$(mktemp) ## Random temp file name

cat<<EOF >$tex_file   ## Print the tex file header
\documentclass[hungarian]{article}
\usepackage{t1enc}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage{listings}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\lstdefinestyle{customasm}{
  belowcaptionskip=1\baselineskip,
  xleftmargin=\parindent,
  language=C,   %% Change this to whatever you write in
  breaklines=true, %% Wrap long lines
  % basicstyle=\footnotesize\ttfamily,
  basicstyle=\ttfamily,
  commentstyle=\itshape\color{Gray},
  stringstyle=\color{Black},
  keywordstyle=\bfseries\color{OliveGreen},
  identifierstyle=\color{blue},
  xleftmargin=-8em,
}
\usepackage[colorlinks=true,linkcolor=blue]{hyperref}
\begin{document}
\tableofcontents

EOF

find . -type f ! -regex ".*/\..*" ! -name ".*" ! -name "*~" ! -name 'src2pdf'|
sed 's/^\..//' | grep "\.c$\|\.h$" | sort |                ## Change ./foo/bar.src to foo/bar.src

while read  i; do                ## Loop through each file
    ./remove_hungarian_accents.py $i > $i.bak479876
    name=${i//_/\\_}             ## escape underscores
    echo "\newpage" >> $tex_file   ## start each section on a new page
    echo "\section{$name}" >> $tex_file  ## Create a section for each filename

   ## This command will include the file in the PDF
    echo "\lstinputlisting[style=customasm]{$i.bak479876}" >>$tex_file
done &&
echo "\end{document}" >> $tex_file &&
pdflatex $tex_file -output-directory . &&
pdflatex $tex_file -output-directory .  ## This needs to be run twice
                                           ## for the TOC to be generated
rm *.bak479876
rm tmp.aux
rm tmp.log
rm tmp.out
rm tmp.toc
mv tmp.pdf all.pdf
